"""Pull request creation helpers."""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from aegis.github.client import GitHubClient, GitHubError


@dataclass
class CreatePRResult:
    number: int
    url: str
    title: str
    head: str
    base: str
    raw: dict[str, Any]


def detect_github_remote(workspace: Path | str) -> tuple[str, str] | None:
    """
    Parse `origin` remote for owner/repo.

    Supports HTTPS and SSH GitHub URLs.
    """
    root = Path(workspace)
    try:
        proc = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            cwd=str(root),
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=15,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if proc.returncode != 0:
        return None
    url = (proc.stdout or "").strip()
    return parse_github_remote_url(url)


def parse_github_remote_url(url: str) -> tuple[str, str] | None:
    u = url.strip().rstrip("/")
    if u.endswith(".git"):
        u = u[:-4]
    # git@github.com:owner/repo
    if u.startswith("git@github.com:"):
        rest = u[len("git@github.com:") :]
        parts = rest.split("/")
        if len(parts) >= 2:
            return parts[0], parts[1]
    # https://github.com/owner/repo
    for prefix in ("https://github.com/", "http://github.com/", "ssh://git@github.com/"):
        if u.startswith(prefix):
            rest = u[len(prefix) :]
            parts = rest.split("/")
            if len(parts) >= 2:
                return parts[0], parts[1]
    return None


def push_branch(
    workspace: Path | str,
    branch: str,
    *,
    remote: str = "origin",
    set_upstream: bool = True,
) -> None:
    """Push *branch* to *remote* (requires credentials configured)."""
    args = ["git", "push"]
    if set_upstream:
        args += ["-u", remote, branch]
    else:
        args += [remote, branch]
    proc = subprocess.run(
        args,
        cwd=str(workspace),
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=180,
    )
    if proc.returncode != 0:
        raise GitHubError(
            f"git push failed: {(proc.stderr or proc.stdout or '').strip()}"
        )


def create_pull_request(
    owner: str,
    repo: str,
    *,
    title: str,
    body: str,
    head: str,
    base: str = "main",
    draft: bool = False,
    client: GitHubClient | None = None,
    token: str | None = None,
) -> CreatePRResult:
    gh = client or GitHubClient(token=token)
    data = gh.create_pull_request(
        owner,
        repo,
        title=title,
        body=body,
        head=head,
        base=base,
        draft=draft,
    )
    return CreatePRResult(
        number=int(data.get("number") or 0),
        url=str(data.get("html_url") or ""),
        title=str(data.get("title") or title),
        head=head,
        base=base,
        raw=data,
    )


def build_pr_body(
    *,
    issue_text: str,
    classification_summary: str = "",
    plan_summary: str = "",
    report_path: str | None = None,
    issue_url: str | None = None,
) -> str:
    """Compose a reasonable PR description."""
    lines = [
        "## Summary",
        "",
        plan_summary or classification_summary or "Autonomous fix by Aegis Engineer.",
        "",
    ]
    if issue_url:
        lines += [f"Closes: {issue_url}", ""]
    lines += [
        "## Issue",
        "",
        "```",
        issue_text[:3000],
        "```",
        "",
        "---",
        "*Generated by [Aegis Engineer](https://github.com/aegis-engineer/aegis-engineer)*",
    ]
    if report_path:
        lines.append(f"*Local report: `{report_path}`*")
    return "\n".join(lines)
