"""Deterministic documentation templates (no LLM required)."""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

from aegis.docs_engine.models import DocReport, DocSurface, SurfaceKind


def _provenance(sources: list[str]) -> str:
    src = ",".join(sources) if sources else "inventory"
    return f"\n\n<!-- aegis:sources={src} generated={datetime.now(UTC).isoformat()} -->\n"


def render_cli_md(surfaces: list[DocSurface], workspace: Path) -> str:
    cmds = [s for s in surfaces if s.kind is SurfaceKind.CLI]
    lines = [
        "# CLI Reference",
        "",
        "Generated by `aegis document` from the project command inventory.",
        "",
        "## Commands",
        "",
        "| Command | Source |",
        "|---------|--------|",
    ]
    sources: list[str] = []
    for s in sorted(cmds, key=lambda x: x.id):
        src = s.path or "—"
        if s.path:
            sources.append(s.path)
        lines.append(f"| `{s.id}` | `{src}` |")
    lines.extend(
        [
            "",
            "## Common usage",
            "",
            "```bash",
            "aegis                  # launch TUI",
            "aegis run \"...\"        # non-interactive agent",
            "aegis serve            # HTTP API",
            "aegis test             # quality gate",
            "aegis document         # living docs",
            "aegis push             # push if gate is SAFE",
            "```",
            "",
            "See also root `README.md` for install and configuration.",
        ]
    )
    return "\n".join(lines) + _provenance(sorted(set(sources)))


def render_api_md(surfaces: list[DocSurface]) -> str:
    routes = [s for s in surfaces if s.kind is SurfaceKind.ROUTE]
    lines = [
        "# HTTP API",
        "",
        "Generated by `aegis document` from Starlette route definitions.",
        "",
        "Base URL (default): `http://127.0.0.1:4096`",
        "",
        "## Routes",
        "",
        "| Method / path | Source |",
        "|---------------|--------|",
    ]
    sources: list[str] = []
    for s in sorted(routes, key=lambda x: x.id):
        if s.path:
            sources.append(s.path)
        lines.append(f"| `{s.id}` | `{s.path or '—'}` |")
    if not routes:
        lines.append("| _(none found)_ | |")
    lines.extend(
        [
            "",
            "## Quick start",
            "",
            "```bash",
            "aegis serve",
            "curl -s http://127.0.0.1:4096/health",
            "```",
            "",
        ]
    )
    return "\n".join(lines) + _provenance(sorted(set(sources)))


def render_architecture_md(surfaces: list[DocSurface], workspace: Path) -> str:
    packages = [s for s in surfaces if s.kind is SurfaceKind.PACKAGE]
    lines = [
        "# Architecture",
        "",
        "Generated by `aegis document` from the package inventory.",
        "",
        f"**Workspace:** `{workspace.name}`",
        "",
        "## Packages",
        "",
        "| Package | Path |",
        "|---------|------|",
    ]
    sources: list[str] = []
    for s in sorted(packages, key=lambda x: x.id):
        if s.path:
            sources.append(s.path)
        lines.append(f"| `{s.id}` | `{s.path or '—'}` |")
    lines.extend(
        [
            "",
            "## High-level flow",
            "",
            "```text",
            "CLI / TUI  →  Agent loop  →  Tools (read/edit/bash/…)",
            "                ↓",
            "         HTTP API (Starlette + SSE)",
            "                ↓",
            "    Quality gate (aegis test) → push gate",
            "```",
            "",
            "See `PHASES.md` for the roadmap and `AI_Software_Engineer_Project_Blueprint.md`",
            "for the full product design.",
            "",
        ]
    )
    return "\n".join(lines) + _provenance(sorted(set(sources)))


def render_gaps_md(report: DocReport) -> str:
    lines = [
        "# Documentation Gaps",
        "",
        f"**Coverage:** {report.coverage:.1%}  ",
        f"**Undocumented:** {report.undocumented_count}  ",
        f"**Stale refs:** {report.stale_count}  ",
        f"**Generated:** {datetime.now(UTC).isoformat()}",
        "",
        "## Gaps",
        "",
    ]
    if not report.gaps:
        lines.append("_No gaps detected._")
    else:
        for g in report.gaps:
            sid = f" `{g.surface_id}`" if g.surface_id else ""
            sug = f" → `{g.suggested_file}`" if g.suggested_file else ""
            lines.append(f"- **{g.kind.value}**{sid}: {g.detail}{sug}")
    lines.append("")
    return "\n".join(lines) + _provenance([])


def render_changelog_snippet(report: DocReport, changed_topics: list[str]) -> str:
    lines = [
        f"## {datetime.now(UTC).date().isoformat()} — aegis document",
        "",
        f"- Coverage: **{report.coverage:.1%}**",
        f"- Undocumented surfaces: {report.undocumented_count}",
        f"- Stale references: {report.stale_count}",
    ]
    if changed_topics:
        lines.append(f"- Updated topics: {', '.join(changed_topics)}")
    lines.append("")
    return "\n".join(lines)


def render_readme_managed_block(surfaces: list[DocSurface]) -> str:
    """Block for insertion between aegis:start:cli and aegis:end:cli markers."""
    cmds = sorted(
        {s.id for s in surfaces if s.kind is SurfaceKind.CLI and not s.id.startswith("(")}
    )
    lines = [
        "<!-- aegis:start:cli -->",
        "### CLI (auto-maintained)",
        "",
        "Key commands:",
        "",
    ]
    for c in cmds[:20]:
        lines.append(f"- `{c}`")
    lines.extend(["", "Full reference: [docs/CLI.md](docs/CLI.md)", "<!-- aegis:end:cli -->"])
    return "\n".join(lines)
